llm_model_path: gpt-4-turbo-preview
max_tokens: 1024
timeout: 600
num_generations: 1
temperature: 0
autobiography_path_for_summary: ./assets/autobiography_chapters.json
autobiography_path_for_rag: ./assets/autobiography/13991012000013_Test.txt
autobiography_pre_summary_path: ./assets/autobiography_pre_summary.json
autobiography_pre_event_path: ./assets/autobiography_pre_event.json