agent_name: Patient
#llm_model_path: gpt-4o-2024-05-13
llm_model_path: gpt-4o
max_tokens: 1024
timeout: 600
num_generations: 1
temperature: 0
patient_id: 'Jane_Eyre'
autobiography_path_for_summary: ./assets/autobiography/jane_eyre/autobiography_chapters_Jane_Eyre.json
autobiography_path_for_rag: ./assets/autobiography/jane_eyre/Jane_Eyre_An_Autobiography.txt
autobiography_pre_summary_path: ./assets/autobiography/jane_eyre/autobiography_pre_summary_Jane_Eyre.json
autobiography_pre_event_path: ./assets/autobiography/jane_eyre/autobiography_pre_event_parsed_Jane_Eyre.json